### ISSUE TITLE
Crash while launching

### ISSUE THREAD

**Issue by Felisinnn** [CircuitLord/ReactiveMusic#15]
1.20.1 fabric 

Crash report: [crash-2024-07-28_02.59.22-client.txt](https://github.com/user-attachments/files/16401870/crash-2024-07-28_02.59.22-client.txt)

Log: https://mclo.gs/YiGQd1z

**Comment by CircuitLord** [comment]
I've seen this crash happen a few times although I'm unclear on what's causing it exactly, can you verify you have a default audio device set and it's playing audio fine without Reactive Music in there?

**Comment by CircuitLord** [comment]
Gotcha alright, will take a look at it!

**Comment by micahhanevich** [comment]
Hey just wanted to add I'm also experiencing this issue. It works fine in some other personal modpacks I've made, but I think it may have something to do with Create. I'll play around with it and get back to this thread on it

**Comment by micahhanevich** [comment]
Got it! The issue is with Ad Astra. If Ad Astra is installed alongside Reactive Music it crashes with this exact error.

**Comment by GeekyBakerBen** [comment]
Seconded - I'm also getting this same crash issue with both Reactive Music and Ad Astra installed. RM used to work fine on my previous modpack which didn't feature Ad Astra.

**Comment by AgentK20** [comment]
Ditto, also seeing this on my pack with Ad Astra

**Comment by AgentK20** [comment]
Quickly glanced through your source: It's because you're overwriting the actual AdvancedPlayer class, while Ad Astra imports the upstream javazoom.jlayer library. Due to mod loading order it seems that your copy of the class gets stomped on, then causing a catastrophic NoSuchFieldError when your code finally runs, crashing the client.

I'd recommend either using a mixin-style modification of jlayer, or fork their library and rename the paths. Overwriting the classes as you're doing is an easy way to have unexpected collisions with any other mod that happens to depend on the same library that you've modded.

**Comment by CircuitLord** [comment]
Gotcha thank you for looking into that

I don't really know anything about MC modding so I probably wouldn't have figured that out 😅 

I'll try to fix that in the next update
